### ISSUE TITLE
Keyboard Issue : The keyboard taking white space in pip view while pip mode 

### ISSUE THREAD

**Issue by alibharmal** [lslv1243/pip_view#6]
The Keyboard showing white Spaces in pip Screen when the keyboard is open in background screen  
Can any pls help with this issue .

**Comment by lslv1243** [comment]
Hi @alibharmal, thanks for using the lib.
You probably forgot to set the `resizeToAvoidBottomInset` while floating like on the example:
```dart
builder: (context, isFloating) => Scaffold(
    resizeToAvoidBottomInset: !isFloating,
```

**Comment by Eimji** [comment]
@lslv1243 you are right! Thanks.
